# Laborator 3
Saptamana 11-15 martie 2019

In [2]:
#ex 2

import numpy as np
def f1(a):
    """This function make the sum for each row of the matrix
    :param a: numpy 2D array
    return:numpy.ndarray
    """
    return np.prod(a, 1)

a = np.array([[7, 1, 2],
              [3, 2, 4],
              [1, 3, 4]])
f1(a)

array([14, 24, 12])

In [5]:
#ex1
import numpy as np
def f2(a):
    """This function show the position in matrix where the value
    is equal with a given value
    :param a: numpy 2D array
    return: tuple
     """
    return np.where(a==4)
    
a = np.array([[0, 1, 2],
              [0, 2, 4],
              [0, 3, 4]])
f2(a)

(array([1, 2], dtype=int64), array([2, 2], dtype=int64))

In [10]:
#ex3
import numpy as np
def f3(a,b):
    """This function show if an element from a matrix, is bigger or equal with
    the value from another matrix situated on the same position
    :param a: numpy 2D array
    :param b: numpy 2D array
    return:numpy.ndarray
    """
    return a>=b
    
a = np.array([[0, 1, 2],
              [0, 2, 4],
              [0, 3, 4]])
b = np.array([[7, 1, 2],
              [3, 2, 4],
              [1, 3, 4]])
f3(a,b)

array([[False,  True,  True],
       [False,  True,  True],
       [False,  True,  True]])

In [13]:
#ex4
import numpy as np
def f4(a):
    """This function returns the positions in array of the biggest number
    :param a:numpy array
    return:tuple
    """
    return np.where(arr == np.amax(arr))

arr=np.array([7,8 ,89, 20,34,23,67,89,0])
f4(arr)

(array([2, 7], dtype=int64),)

In [17]:
import numpy as np
def multiply(arr):
    """Multiply the numbers which ar lower than 100
    :param a: np.array
    return: numpy.ndarray"""
    arr[arr<100] *= 2
    return arr
def ciclare(arr):
    """
    In this function, the "multiply" function is applied until 
    there are no elements smaller than 100. Then returns the numbers
    between 150 and 200
    :param arr: np.array
    return:numpy.ndarray
    """
    while arr[arr<100].any():
        arr[arr<100]*=2
    return(arr[(np.logical_and(arr>150, arr<200))])

arr = np.array([230, 284,10, 39, 76])
multiply(arr)
ciclare(arr)

[230 284  20  78 152]


array([160, 156, 152])

In [10]:
#ex 6
""" This function peak the biggest numbers on the same position 
from two diffrent arrays
:param a: np.array
:param b: np.array
return: 'numpy.ndarray
"""
def maxim(a,b):
    return np.maximum(a,b)

a = np.array([3, 7, 9, 13, -10, 200, 3])
b = np.array([4, 5, -9, 100, 300, 230, 1])
maxim(a,b)

<class 'numpy.ndarray'>


array([  4,   7,   9, 100, 300, 230,   3])

In [37]:
#ex7
import numpy as np
def met1(a):
    """This function calculates how long it takes to calculate a sum, 
    starting from a matrix, making a copy of it, replacing the nan values with 0 and then actually make the sum.
    :param a: numpyy 2D array
    return: """
    %timeit np.nan_to_num(np.copy(a)).sum()
    
def met2(a):
    """Using the nansum function, met2 calculates how long it takes to make the sum of all values from matrix
    :param a: numpy 2D array
    return: 
    """
    %timeit sum2=np.nansum(a)

def met3(a):
    """This function calculates how long it takes to make a sum with all values from a matrix, excluding 
    those values equal to nan
    :param a: numpy 2D array
    return: """
    %timeit sum3=a[np.isnan(a)==False].sum()
    
a = np.array([[7, 1, 2],
            [3, 2, 4],
            [1, 3, np.NaN]])
met1(a)
met2(a)
met3(a)


21.9 µs ± 1.95 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)
11.3 µs ± 4.4 µs per loop (mean ± std. dev. of 7 runs, 100000 loops each)
7.42 µs ± 1.36 µs per loop (mean ± std. dev. of 7 runs, 100000 loops each)


## Exercitii simple folosind API de NumPy  

Nota: in rezolvarea exercitiilor se vor folosi cat mai mult functii NumPy vectorizate. Functiile scrise de voi vor fi documentate cu docstrings (tutoriale: Docstrings in Python, urmati NumPy Style Python Docstrings). Folositi type annotations. Utilizati doar pachetele NumPy si SciPy.

1. (0.5 puncte) Folosind functia `np.where`, determinati care sunt liniile si coloanele care contin un element dat intr-o matrice. 
1. (0.5 puncte) Pentru o matrice de numere, sa se determine produsul elementelor pe linii.
1. (0.5 puncte) Determinati daca toate elementele unei matrice `a` sunt mai mari sau egale decat toate de pe pozitiile corespondente din `b`.
1. (0.5 puncte) Pentru un vector de numere, care sunt *toate pozitiile* pe care apare valoarea maxima? Folositi functie NumPy.
1. (0.5 puncte) Se considera vectorul: `a = np.array([230, 10, 284, 39, 76])`. Folosind indexarea logica, sa se inmulteasca elementele din vector care sunt mai mici ca 100 cu 2 (restul raman neschimbate). Folosind ciclare, sa se aplice aceeasi operatie pana cand toate elementele devin mai mari ca 100. Sa se afiseze din vectorul final elementele care sunt mai mari de 150 si mai mici de 200.
1. (0.5 puncte) Sa se scrie o functie care preia doi vectori de aceeasi lungime si returneaza maximele pe pozitiile corespunzatoare:
```python
a = np.array([3, 7, 9, 13, -10, 200, 3])
b = np.array([4, 5, -9, 100, 300, 230, 1])
pair_max(a, b)
#iesire dorita: 
array([  4,   7,   9, 100, 300, 230,   3])
```
1. (1 punct) Sa se calculeze suma elementelor non-NaN intr-un 2d numpy array, in 3 feluri. Folosind comanda magica `%%timeit` [Built-in magic commands](http://ipython.readthedocs.io/en/stable/interactive/magics.html#cell-magics), [IPython Magic Commands](https://jakevdp.github.io/PythonDataScienceHandbook/01.03-magic-commands.html), sa se determine care e mai rapida.
    1. Peste o copie a tabelului initial (functia membru `copy()` a unui tablou) se suprascriu elementele nan cu 0, apoi se face suma;
    1. Folosind functia `np.nansum`;
    1. Folosind indiciere booleana si functia `np.isnan`, se determina colectia elementelor non-nan si se calculeaza suma lor in mod obisnuit.
1. (1 punct) Incarcati setul de date Iris, de la adresa 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data', folosind `np.genfromtxt`.  Alegeti aleator 10 pozitii in matricea de 150 linii si 4 coloane (omiteti ultima coloana, de tip text), setati aceste valori pe NaN. Construiti o functie care, primid la intrare o matrice, returneaza un tuplu cu indicii de linie respectiv de coloana in care se gasesc valori NaN.
1. (1 punct) Construiti o functie care, primind o matrice, determina pe ce pozitii se afla valorile in afara unui interval \[min, max\] dat prin parametri. 
1. (1 punct) Sa se construiasca o functie care returneaza cele mai mari `k` valori dintr-un vector de cel putin `k` elemente, impreuna cu pozitiile lor. 

In [4]:
#ex9
import numpy as np
def interval(a, min, max):
    """
    This function returns positions of the values lower than a min value
    and higher than a max value
    :param a: numpy 2D array
    return: numpy.ndarray
    """
    return np.argwhere(np.logical_or(a < min, a>max))
a = np.array([[10, 13, 23],
                [30, 22, 14],
                [20, 31, 24]])
interval(a, 10,20)

<class 'numpy.ndarray'>


array([[0, 2],
       [1, 0],
       [1, 1],
       [2, 1],
       [2, 2]], dtype=int64)

In [7]:
#ex10
def k_valori(a,k):
    """
    The function returns the biggest k values from the array
    :param a: an numpy array
    return: numpy.ndarray
    """
    return (a[np.argsort(a)[-k:]])
    
arr = np.array([58, 50, 40,  9, 92,  5, 91, 43, 2,5,
                90, 60, 85, 49, 38, 76, 51, 38,
                 14, 30, 61])
k_valori(arr,5)

<class 'numpy.ndarray'>


array([76, 85, 90, 91, 92])

**Precizari:**
1. Se acorda 3 puncte din oficiu.
1. Tema se va prezenta in sapatamana 18-22 martie. 
1. Modalitatea de predare a temei: 
    1. se vor forma si se va lucra in echipe de cate doua persoane (in cazul in care nu se poate, se va lucra individual)
    2. exercitiile rezolvate se vor comite pe un repository **privat** de [Github](https://github.com/), la care vor avea doar acces membrii echipei si profesorii, Lucian Mircea Sasu (cont github: lmsasu) respectiv Arpad Kerestely (cont github: akerestely)
    3. repository-ul va contine un fisier "readme.md" (in radacina repository-ului) in care vor fi mentionati autorii temelor, cu nume complet si grupa din care fac parte.