# Laborator 3
Saptamana 11-15 martie 2019

In [47]:
#ex 2
"""Returns the sum \ row"""
import numpy as np
def f1(a):
    return np.prod(a, 1)

a = np.array([[7, 1, 2],
              [3, 2, 4],
              [1, 3, 4]])
f1(a)

array([14, 24, 12])

In [2]:
#ex1
import numpy as np
"""Peek the position in a matrix, where
appear a given value"""
a = np.array([[0, 1, 2],
              [0, 2, 4],
              [0, 3, 4]])
np.where(a==4)

(array([1, 2], dtype=int64), array([2, 2], dtype=int64))

In [3]:
#ex3
import numpy as np
"""For two 2D arrays, it shows if values on 
the same position are eqal"""
a = np.array([[0, 1, 2],
              [0, 2, 4],
              [0, 3, 4]])
b = np.array([[7, 1, 2],
              [3, 2, 4],
              [1, 3, 4]])
a==b

array([[False,  True,  True],
       [False,  True,  True],
       [False,  True,  True]])

In [49]:
#ex4
import numpy as np
"""Peak the positions of the  biggest number """
arr=np.array([7,8 ,89, 20,34,23,67,89,0])
print(np.where(arr == np.amax(arr)))

(array([2, 7], dtype=int64),)


In [41]:
"""Multiply the numbers<100 while they are exist"""
"""Display the umbers between 150 and 200"""
arr = np.array([230, 284,10, 39, 76])
while np.all(arr>100) ==False:
    arr [arr<100]*=2
print(arr[(arr>150) & (arr<200)])

[160 156 152]


In [50]:
#ex 6
"""Peak the boggest numbers on the same position 
from two diffrent arrays"""
a = np.array([3, 7, 9, 13, -10, 200, 3])
b = np.array([4, 5, -9, 100, 300, 230, 1])
print(np.maximum(a,b))

[  4   7   9 100 300 230   3]


In [54]:
#ex7
import numpy as np
a = np.array([[7, 1, 2],
              [3, 2, 4],
              [1, 3, np.NaN]])
#metoda 1

b=np.copy(a)
b=np.nan_to_num(a)
%timeit sum1=b.sum()
#print('Sum1: ', sum1)

#metoda 2
%timeit sum2=np.nansum(a)
#print('Sum2: ',sum2)

#metoda 3
%timeit sum3=a[np.isnan(a)==False].sum()
#print('Sum3: ', sum3)


2.98 µs ± 239 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
10.5 µs ± 475 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
6.59 µs ± 750 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


## Exercitii simple folosind API de NumPy  

Nota: in rezolvarea exercitiilor se vor folosi cat mai mult functii NumPy vectorizate. Functiile scrise de voi vor fi documentate cu docstrings (tutoriale: Docstrings in Python, urmati NumPy Style Python Docstrings). Folositi type annotations. Utilizati doar pachetele NumPy si SciPy.

1. (0.5 puncte) Folosind functia `np.where`, determinati care sunt liniile si coloanele care contin un element dat intr-o matrice. 
1. (0.5 puncte) Pentru o matrice de numere, sa se determine produsul elementelor pe linii.
1. (0.5 puncte) Determinati daca toate elementele unei matrice `a` sunt mai mari sau egale decat toate de pe pozitiile corespondente din `b`.
1. (0.5 puncte) Pentru un vector de numere, care sunt *toate pozitiile* pe care apare valoarea maxima? Folositi functie NumPy.
1. (0.5 puncte) Se considera vectorul: `a = np.array([230, 10, 284, 39, 76])`. Folosind indexarea logica, sa se inmulteasca elementele din vector care sunt mai mici ca 100 cu 2 (restul raman neschimbate). Folosind ciclare, sa se aplice aceeasi operatie pana cand toate elementele devin mai mari ca 100. Sa se afiseze din vectorul final elementele care sunt mai mari de 150 si mai mici de 200.
1. (0.5 puncte) Sa se scrie o functie care preia doi vectori de aceeasi lungime si returneaza maximele pe pozitiile corespunzatoare:
```python
a = np.array([3, 7, 9, 13, -10, 200, 3])
b = np.array([4, 5, -9, 100, 300, 230, 1])
pair_max(a, b)
#iesire dorita: 
array([  4,   7,   9, 100, 300, 230,   3])
```
1. (1 punct) Sa se calculeze suma elementelor non-NaN intr-un 2d numpy array, in 3 feluri. Folosind comanda magica `%%timeit` [Built-in magic commands](http://ipython.readthedocs.io/en/stable/interactive/magics.html#cell-magics), [IPython Magic Commands](https://jakevdp.github.io/PythonDataScienceHandbook/01.03-magic-commands.html), sa se determine care e mai rapida.
    1. Peste o copie a tabelului initial (functia membru `copy()` a unui tablou) se suprascriu elementele nan cu 0, apoi se face suma;
    1. Folosind functia `np.nansum`;
    1. Folosind indiciere booleana si functia `np.isnan`, se determina colectia elementelor non-nan si se calculeaza suma lor in mod obisnuit.
1. (1 punct) Incarcati setul de date Iris, de la adresa 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data', folosind `np.genfromtxt`.  Alegeti aleator 10 pozitii in matricea de 150 linii si 4 coloane (omiteti ultima coloana, de tip text), setati aceste valori pe NaN. Construiti o functie care, primid la intrare o matrice, returneaza un tuplu cu indicii de linie respectiv de coloana in care se gasesc valori NaN.
1. (1 punct) Construiti o functie care, primind o matrice, determina pe ce pozitii se afla valorile in afara unui interval \[min, max\] dat prin parametri. 
1. (1 punct) Sa se construiasca o functie care returneaza cele mai mari `k` valori dintr-un vector de cel putin `k` elemente, impreuna cu pozitiile lor. 

In [59]:
#ex9
def interval(a):
    b=(a>10) & (a>30)
    return b
a = np.array([[10, 13, 23],
                [30, 22, 14],
                [20, 31, 24]])

interval(a)

array([[False, False, False],
       [False, False, False],
       [False,  True, False]])

In [57]:
#ex10
def k_valori(a,k):
    print (a[np.argsort(a)[-k:]])
    
arr = np.array([58, 50, 40,  9, 92,  5, 91, 43, 2,5,
                90, 60, 85, 49, 38, 76, 51, 38,
                 14, 30, 61])
k_valori(arr,5)



[76 85 90 91 92]


**Precizari:**
1. Se acorda 3 puncte din oficiu.
1. Tema se va prezenta in sapatamana 18-22 martie. 
1. Modalitatea de predare a temei: 
    1. se vor forma si se va lucra in echipe de cate doua persoane (in cazul in care nu se poate, se va lucra individual)
    2. exercitiile rezolvate se vor comite pe un repository **privat** de [Github](https://github.com/), la care vor avea doar acces membrii echipei si profesorii, Lucian Mircea Sasu (cont github: lmsasu) respectiv Arpad Kerestely (cont github: akerestely)
    3. repository-ul va contine un fisier "readme.md" (in radacina repository-ului) in care vor fi mentionati autorii temelor, cu nume complet si grupa din care fac parte.